# -*- coding: utf-8 -*-
"""Document_Translator_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TEcMqai8oKSeBNrW-nmW3cdvIZ1shJKP
"""

# Cell 1: Install dependencies
# ── Install dependencies ──────────────────────────────────────────────────────
# Only run pip install when executed interactively in Colab, not when imported as a module
if __name__ == '__main__' or 'google.colab' in __import__('sys').modules:
    try:
        import IPython
        IPython.get_ipython().run_line_magic('pip', 'install transformers sentencepiece python-docx pdfplumber odfpy striprtf gradio PyMuPDF')
    except Exception:
        pass

# Cell 2: Imports
# ── Imports ───────────────────────────────────────────────────────────────────
import os
import re
import mimetypes
import csv
import io
from collections import deque
from pathlib import Path

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from docx import Document
import fitz  # PyMuPDF for PDF manipulation

# Cell 3: Model Setup
# ── Model Setup ───────────────────────────────────────────────────────────────
import torch
model_name = "facebook/nllb-200-distilled-600M"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Move to GPU if available for faster translation
device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)
print(f"✅ Model loaded on: {device}")

# Cell 4: Language Codes
# ── Language Codes ────────────────────────────────────────────────────────────
LANGUAGES = {
    "English":  "eng_Latn",
    "Cebuano":  "ceb_Latn",
    "Filipino": "tgl_Latn",
}

# Cell 5 (v3 – Block-Quality Filter): File Readers
# ─────────────────────────────────────────────────────────────────────────────
import re as _re

# ── helpers ───────────────────────────────────────────────────────────────────

def _is_garbage_block(text, bbox, page_width, page_height):
    """
    Returns True if a text block should be SKIPPED:
      - Pure numbers / page numbers  (e.g. '4', '4 4', '22 22')
      - URL-only blocks
      - Fewer than 3 meaningful words
      - Very narrow blocks (likely drawing artefacts)
      - Suspiciously tiny font remnants (bbox height < 4px)
    """
    stripped = text.strip()
    # page-number pattern: '4', '4 4', '21 21'
    if _re.fullmatch(r'\d+\s*\d*', stripped):
        return True
    # URL-only
    if stripped.lower().startswith('http') or stripped.lower().startswith('www'):
        return True
    # Fewer than 3 words
    words = [w for w in stripped.split() if _re.search(r'[a-zA-Z\u0080-\uFFFF]', w)]
    if len(words) < 3:
        return True
    # Tiny bbox height (artefact)
    x0, y0, x1, y1 = bbox
    if (y1 - y0) < 4:
        return True
    return False


def _detect_columns(blocks, page_width):
    """
    Split blocks into left / right columns based on their x-center.
    Returns (left_blocks, right_blocks).
    If the page has no clear columnar split, returns (all_blocks, []).

    .. deprecated::
        Use ``detect_columns()`` instead.  This function is kept only for
        backwards-compatibility and is no longer called by the pipeline.
    """
    mid = page_width / 2
    left  = [b for b in blocks if (b['position'][0] + b['position'][2]) / 2 < mid]
    right = [b for b in blocks if (b['position'][0] + b['position'][2]) / 2 >= mid]
    # Only treat as two-column if both sides are substantial
    if len(left) >= 2 and len(right) >= 2:
        return left, right
    return blocks, []


def detect_columns(blocks: list, page_width: float) -> list:
    """
    Detect 1, 2, or 3 columns on a PDF page using x-coordinate gap analysis
    and return all blocks in correct reading order.

    Algorithm (Requirements 10.1 – 10.5):
    1. Separate full-width blocks (width >= 90% of page_width) from the rest.
    2. Sort the remaining (columnar candidate) blocks by their left x-coordinate.
    3. Scan for horizontal gaps >= 10% of page_width between consecutive blocks
       (sorted by x0) to identify up to 2 gap positions → up to 3 columns.
    4. Assign each columnar block to a column based on the gap boundaries.
    5. Fall back to single-column if any candidate column has < 2 blocks.
    6. Sort blocks within each column by top y-coordinate.
    7. Merge columns left-to-right, interleaving full-width blocks at their
       correct y-position relative to the columnar blocks.

    Parameters
    ----------
    blocks : list[dict]
        Blocks for a single page, each with a ``"position"`` key
        ``[x0, y0, x1, y1]``.
    page_width : float
        Width of the page in PDF user-space units.

    Returns
    -------
    list[dict]
        All blocks in reading order (top-to-bottom, left-to-right within
        each column, full-width blocks interleaved at their y-position).
    """
    if not blocks:
        return []

    gap_threshold = 0.10 * page_width
    full_width_threshold = 0.90 * page_width

    # ── Step 1: Separate full-width blocks from columnar candidates ──────────
    full_width = []
    columnar = []
    for b in blocks:
        x0, y0, x1, y1 = b["position"]
        block_width = x1 - x0
        if block_width >= full_width_threshold:
            full_width.append(b)
        else:
            columnar.append(b)

    # Sort full-width blocks by top y-coordinate
    full_width.sort(key=lambda b: b["position"][1])

    # ── Step 2: If no columnar blocks, return full-width sorted by y ─────────
    if not columnar:
        return full_width

    # ── Step 3: Find gap positions using x-sorted blocks ────────────────────
    # Sort columnar blocks by their left x-coordinate to find gaps
    x_sorted = sorted(columnar, key=lambda b: b["position"][0])

    # Find up to 2 gaps (supporting up to 3 columns)
    gap_positions = []  # list of x-values where a column boundary exists
    for i in range(len(x_sorted) - 1):
        right_edge_of_current = x_sorted[i]["position"][2]   # x1 of block i
        left_edge_of_next     = x_sorted[i + 1]["position"][0]  # x0 of block i+1
        gap = left_edge_of_next - right_edge_of_current
        if gap >= gap_threshold:
            # Record the midpoint of the gap as the boundary
            boundary = (right_edge_of_current + left_edge_of_next) / 2.0
            # Avoid recording duplicate/adjacent boundaries
            if not gap_positions or (boundary - gap_positions[-1]) > gap_threshold:
                gap_positions.append(boundary)
            if len(gap_positions) == 2:
                break  # max 3 columns → max 2 boundaries

    # ── Step 4: Assign columnar blocks to columns ────────────────────────────
    if not gap_positions:
        # No gaps found → single column
        columns = [columnar]
    elif len(gap_positions) == 1:
        boundary = gap_positions[0]
        col0 = [b for b in columnar if b["position"][2] <= boundary or
                (b["position"][0] + b["position"][2]) / 2 < boundary]
        col1 = [b for b in columnar if b not in col0]
        columns = [col0, col1]
    else:
        b0, b1 = gap_positions[0], gap_positions[1]
        col0 = [b for b in columnar if (b["position"][0] + b["position"][2]) / 2 < b0]
        col2 = [b for b in columnar if (b["position"][0] + b["position"][2]) / 2 >= b1]
        col1 = [b for b in columnar if b not in col0 and b not in col2]
        columns = [col0, col1, col2]

    # ── Step 5: Fall back to single-column if any column has < 2 blocks ─────
    if any(len(col) < 2 for col in columns):
        columns = [columnar]

    # ── Step 6: Sort blocks within each column by top y-coordinate ──────────
    for col in columns:
        col.sort(key=lambda b: b["position"][1])

    # ── Step 7: Merge columns left-to-right, interleave full-width blocks ────
    # Build the flat columnar reading order (left col first, then center, then right)
    columnar_ordered = []
    for col in columns:
        columnar_ordered.extend(col)

    # Now interleave full-width blocks at their correct y-position.
    # A full-width block with top y=Y should appear before any columnar block
    # whose top y > Y (Requirement 10.4).
    result = []
    fw_idx = 0
    for block in columnar_ordered:
        block_y = block["position"][1]
        # Insert any full-width blocks that should come before this columnar block
        while fw_idx < len(full_width) and full_width[fw_idx]["position"][1] <= block_y:
            result.append(full_width[fw_idx])
            fw_idx += 1
        result.append(block)
    # Append any remaining full-width blocks at the end
    while fw_idx < len(full_width):
        result.append(full_width[fw_idx])
        fw_idx += 1

    return result


def read_docx(file_path):
    """Read paragraphs and tables from a .docx file with full style and formatting metadata.

    Extracts per paragraph (Requirements 7.1, 7.4, 7.5, 7.6):
      - style_name  : para.style.name
      - alignment   : para.alignment
      - space_before: para.paragraph_format.space_before
      - space_after : para.paragraph_format.space_after
      - font_color  : run.font.color.rgb of the first run that has a color set

    Extracts all tables (Requirements 8.1):
      - Each cell stored as a table_cell block with row/col/span metadata
      - Table cells appended after paragraph blocks
    """
    doc = Document(file_path)
    blocks = []

    # ── Paragraph blocks ──────────────────────────────────────────────────────
    for para in doc.paragraphs:
        text = para.text.strip()
        if text and len(text.split()) >= 3:
            # Collect run-level font color: use the first run that has an
            # explicit RGB color set directly on the run (not inherited).
            font_color = None
            for run in para.runs:
                try:
                    rgb = run.font.color.rgb
                    if rgb is not None:
                        font_color = rgb
                        break
                except Exception:
                    pass

            style_info = {
                "bold":        para.runs[0].bold      if para.runs else False,
                "font_size":   para.runs[0].font.size if para.runs else None,
                # Paragraph-level style metadata (Req 7.1, 7.4, 7.5, 7.6)
                "style_name":  para.style.name if para.style else None,
                "alignment":   para.alignment,
                "space_before": para.paragraph_format.space_before,
                "space_after":  para.paragraph_format.space_after,
                "font_color":  font_color,
            }
            blocks.append({"type": "paragraph", "text": text, "style": style_info})

    # ── Table blocks (Requirement 8.1) ────────────────────────────────────────
    for table_index, table in enumerate(doc.tables):
        for row_idx, row in enumerate(table.rows):
            for col_idx, cell in enumerate(row.cells):
                cell_text = cell.text.strip()

                # Collect run-level bold and font_size from the first run
                # that has an explicit value set.
                cell_bold = None
                cell_font_size = None
                for para in cell.paragraphs:
                    for run in para.runs:
                        if cell_bold is None and run.bold is not None:
                            cell_bold = run.bold
                        if cell_font_size is None and run.font.size is not None:
                            cell_font_size = run.font.size
                        if cell_bold is not None and cell_font_size is not None:
                            break
                    if cell_bold is not None and cell_font_size is not None:
                        break

                # Determine row_span and col_span from the underlying XML.
                # python-docx exposes merged cells by repeating the same cell
                # object; we derive spans from the tc XML element attributes.
                try:
                    tc = cell._tc
                    # gridSpan gives the number of columns the cell spans
                    grid_span_el = tc.find(
                        './/{http://schemas.openxmlformats.org/wordprocessingml/2006/main}gridSpan'
                    )
                    col_span = int(grid_span_el.get(
                        '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}val', 1
                    )) if grid_span_el is not None else 1

                    # vMerge gives vertical merge info; count consecutive vMerge
                    # cells below this one to determine row_span.
                    vmerge_el = tc.find(
                        './/{http://schemas.openxmlformats.org/wordprocessingml/2006/main}vMerge'
                    )
                    if vmerge_el is not None:
                        val = vmerge_el.get(
                            '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}val', ''
                        )
                        if val == 'restart':
                            # Count how many rows below continue this merge
                            row_span = 1
                            for next_row in table.rows[row_idx + 1:]:
                                if col_idx < len(next_row.cells):
                                    next_tc = next_row.cells[col_idx]._tc
                                    next_vm = next_tc.find(
                                        './/{http://schemas.openxmlformats.org/wordprocessingml/2006/main}vMerge'
                                    )
                                    if next_vm is not None and next_vm.get(
                                        '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}val', ''
                                    ) != 'restart':
                                        row_span += 1
                                    else:
                                        break
                        else:
                            # Continuation cell — skip to avoid duplicates
                            continue
                    else:
                        row_span = 1
                except Exception:
                    col_span = 1
                    row_span = 1

                blocks.append({
                    "type":        "table_cell",
                    "text":        cell_text,
                    "table_index": table_index,
                    "row":         row_idx,
                    "col":         col_idx,
                    "row_span":    row_span,
                    "col_span":    col_span,
                    "style": {
                        "bold":      cell_bold,
                        "font_size": cell_font_size,
                    },
                })

    return blocks


def read_pdf(file_path, column_mode="auto"):
    """
    Read text blocks from a PDF with:
      - Accurate full-block bounding boxes (get_text 'dict')
      - Garbage-block filtering (artefacts, page numbers, URLs)
      - Two-column detection  (column_mode: 'auto'|'single'|'left'|'right')

    column_mode:
      'auto'   – detect columns automatically; translate ALL text found
      'single' – treat entire page as one column
      'left'   – only translate left-column text (useful for bilingual PDFs
                 where the left side is the source language)
      'right'  – only translate right-column text
    """
    blocks = []
    doc = fitz.open(file_path)

    for page_num in range(len(doc)):
        page = doc[page_num]
        pw   = page.rect.width
        ph   = page.rect.height

        page_dict = page.get_text(
            "dict",
            flags=fitz.TEXT_PRESERVE_WHITESPACE | fitz.TEXT_PRESERVE_LIGATURES
        )

        raw_blocks = []
        for rb in page_dict.get("blocks", []):
            if rb.get("type") != 0:
                continue
            lines = rb.get("lines", [])
            if not lines:
                continue

            parts = []
            dom_size  = 11.0
            dom_color = 0
            dom_bold  = False
            dom_font  = "helv"  # default; overwritten by the dominant span
            for line in lines:
                lt = ""
                for span in line.get("spans", []):
                    st = span.get("text", "")
                    if st.strip():
                        lt += st
                        dom_size  = span.get("size",  dom_size)
                        dom_color = span.get("color", dom_color)
                        dom_bold  = bool(span.get("flags", 0) & 2**4)
                        # Capture the font name from the dominant (last
                        # non-empty) span — Requirement 4.1 / 4.5.
                        span_font = span.get("font", "")
                        if span_font:
                            dom_font = span_font
                if lt.strip():
                    parts.append(lt.strip())

            block_text = " ".join(parts).strip()
            if not block_text:
                continue

            bbox = list(rb["bbox"])

            if _is_garbage_block(block_text, bbox, pw, ph):
                continue

            dom_size = max(6.0, min(float(dom_size or 11.0), 72.0))

            raw_blocks.append({
                "type":     "paragraph",
                "text":     block_text,
                "position": bbox,
                "page":     page_num,
                "style":    {"font_size": dom_size, "font": dom_font,
                             "color": dom_color, "bold": dom_bold},
            })

        # Column filtering
        if column_mode == "single" or len(raw_blocks) == 0:
            selected = raw_blocks
        elif column_mode == "auto":
            # Use the new gap-analysis column detector (Requirements 10.1–10.5).
            # detect_columns() returns all blocks in correct reading order
            # (full-width blocks interleaved, columns merged left-to-right).
            selected = detect_columns(raw_blocks, pw)
        else:
            # 'left' / 'right' modes still use the legacy x-center split so
            # that bilingual-PDF workflows (translate only one side) continue
            # to work unchanged.
            left_blocks, right_blocks = _detect_columns(raw_blocks, pw)
            if column_mode == "left":
                selected = left_blocks
            else:   # 'right'
                selected = right_blocks

        blocks.extend(selected)

    doc.close()
    return blocks


def read_txt(file_path):
    with open(file_path, "r", encoding="utf-8", errors="replace") as f:
        raw = f.read()
    paragraphs = [p.strip() for p in _re.split(r'\n{2,}', raw) if p.strip()]
    if not paragraphs:
        paragraphs = [l.strip() for l in raw.splitlines() if l.strip()]
    return [{"type": "paragraph", "text": p, "style": {}} for p in paragraphs
            if len(p.split()) >= 3]


def read_rtf(file_path):
    from striprtf.striprtf import rtf_to_text
    with open(file_path, "r", encoding="utf-8", errors="replace") as f:
        raw = f.read()
    plain = rtf_to_text(raw)
    paragraphs = [p.strip() for p in plain.splitlines() if p.strip()]
    return [{"type": "paragraph", "text": p, "style": {}} for p in paragraphs
            if len(p.split()) >= 3]


def read_odt(file_path):
    from odf.opendocument import load as odf_load
    from odf.text import P
    from odf import teletype
    doc = odf_load(file_path)
    blocks = []
    for para in doc.getElementsByType(P):
        text = teletype.extractText(para).strip()
        if text and len(text.split()) >= 3:
            blocks.append({"type": "paragraph", "text": text, "style": {}})
    return blocks


def read_csv(file_path):
    rows = []
    with open(file_path, "r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.reader(f)
        for row in reader:
            rows.append(row)
    return {"type": "csv", "data": rows}

# Cell 6: Format Dispatcher
# ── Format Dispatcher ─────────────────────────────────────────────────────────

READERS = {
    ".docx": read_docx,
    ".pdf":  read_pdf,
    ".txt":  read_txt,
    ".md":   read_txt,
    ".rtf":  read_rtf,
    ".odt":  read_odt,
    ".csv":  read_csv,
}

def analyze_document(file_path, pdf_column_mode="auto"):
    """Route the file to the correct reader based on its extension."""
    ext = os.path.splitext(file_path)[1].lower()
    reader = READERS.get(ext)
    if reader is None:
        supported = ", ".join(READERS.keys())
        raise ValueError(f"Unsupported file type '{ext}'. Supported: {supported}")
    print(f"  📂 Detected format: {ext}")
    if ext == ".pdf":
        return reader(file_path, column_mode=pdf_column_mode), ext
    return reader(file_path), ext

# Cell 7 (v3 – Anti-Hallucination): Translation Helpers
# ─────────────────────────────────────────────────────────────────────────────
import re as _re2

# ── Post-processing ───────────────────────────────────────────────────────────

def _remove_repetition_loops(text, max_repeat=3):
    """
    Detect and strip repeated phrase loops that NLLB sometimes generates.
    Example: 'What are possible answers? What are possible answers? ...' × 40

    Strategy:
      1. Split into sentences.
      2. Keep a sentence only if it hasn't appeared in the last `max_repeat` sentences.
      3. Hard-stop when we see the same sentence for the 2nd time.
    """
    sentences = _re2.split(r'(?<=[.!?])\s+', text.strip())
    seen   = {}
    result = []
    for s in sentences:
        key = s.strip().lower()
        if not key:
            continue
        count = seen.get(key, 0)
        if count >= max_repeat:
            break   # hard-stop: this is a loop
        seen[key] = count + 1
        result.append(s)
    return " ".join(result)


class Glossary_Store:
    """
    Holds source→target term pairs and applies post-translation substitution.

    Raises ValueError on duplicate source terms (case-insensitive).
    Raises ValueError when len(pairs) > 1000.
    """

    def __init__(self, pairs: list | None = None):
        """
        pairs: list of (source_term, target_term).
        Raises ValueError if duplicates exist (case-insensitive source key).
        Raises ValueError if len(pairs) > 1000.
        """
        if pairs is None:
            pairs = []

        if len(pairs) > 1000:
            raise ValueError(
                f"Glossary_Store: too many term pairs ({len(pairs)}); maximum is 1000."
            )

        self._terms: list[tuple[str, str]] = []
        seen: dict[str, str] = {}  # lowercase key → original source term

        for source, target in pairs:
            key = source.lower()
            if key in seen:
                raise ValueError(
                    f"Glossary_Store: duplicate source term '{source}' "
                    f"(already registered as '{seen[key]}')."
                )
            seen[key] = source
            self._terms.append((source, target))

        # Pre-compile a single regex that matches any source term as a whole word.
        # Terms are sorted longest-first so longer matches take priority.
        if self._terms:
            sorted_terms = sorted(self._terms, key=lambda p: len(p[0]), reverse=True)
            pattern = "|".join(
                r"\b" + re.escape(src) + r"\b" for src, _ in sorted_terms
            )
            self._regex = re.compile(pattern, re.IGNORECASE)
            # Map lowercase source → target for fast lookup
            self._lookup: dict[str, str] = {
                src.lower(): tgt for src, tgt in sorted_terms
            }
        else:
            self._regex = None
            self._lookup = {}

    def apply(self, text: str) -> str:
        """
        Replace whole-word occurrences of each source term in `text`
        with the corresponding target term, preserving capitalisation.
        Returns the substituted text.
        """
        if self._regex is None:
            return text

        def _replace(match: re.Match) -> str:
            original_token = match.group(0)
            target_term = self._lookup[original_token.lower()]
            return self._match_case(original_token, target_term)

        return self._regex.sub(_replace, text)

    @staticmethod
    def _match_case(original_token: str, target_term: str) -> str:
        """Apply capitalisation pattern of original_token to target_term."""
        if original_token.isupper():
            return target_term.upper()
        if original_token.istitle():
            return target_term.title()
        if original_token.islower():
            return target_term.lower()
        # Any other pattern → return target as stored
        return target_term


# ── Font_Mapper ───────────────────────────────────────────────────────────────

class Font_Mapper:
    """
    Maps PDF font names to usable font identifiers for ``insert_textbox()``.

    Resolution order (Requirements 4.1 – 4.5):
    1. Case-insensitive exact match against ``embedded_fonts`` → return ``font_name``
       as-is so PyMuPDF uses the embedded font directly.
    2. Keyword classification:
       - sans-serif keywords → ``"helv"``  (Helvetica)
       - serif keywords      → ``"tiro"``  (Times-Roman)
       - mono keywords       → ``"cour"``  (Courier)
    3. Unknown font or any exception → return ``"helv"`` and log a warning.
    """

    SANS_SERIF_KEYWORDS: set = {
        "arial", "helvetica", "calibri", "verdana", "tahoma", "gothic", "sans"
    }
    SERIF_KEYWORDS: set = {
        "times", "georgia", "garamond", "palatino", "roman", "serif", "minion"
    }
    MONO_KEYWORDS: set = {
        "courier", "mono", "consolas", "menlo", "inconsolata"
    }

    def resolve(self, font_name: str, embedded_fonts: set,
                page: int = 0, bbox=None) -> str:
        """
        Return the fontname string to pass to ``insert_textbox()``.

        Parameters
        ----------
        font_name : str
            The dominant font name extracted from the block's span metadata.
        embedded_fonts : set[str]
            The set of font names embedded in the original PDF page, obtained
            via ``fitz.Document.get_page_fonts()``.
        page : int
            Page number (0-based) — used only in warning messages.
        bbox : sequence or None
            Block bounding box — used only in warning messages.

        Returns
        -------
        str
            A font identifier suitable for ``insert_textbox()``.
        """
        try:
            # ── Step 1: case-insensitive exact match against embedded fonts ──
            font_name_lower = font_name.lower()
            for ef in embedded_fonts:
                if ef.lower() == font_name_lower:
                    return font_name  # use the original casing as stored

            # ── Step 2: keyword classification ───────────────────────────────
            fn_lower = font_name_lower
            for keyword in self.SANS_SERIF_KEYWORDS:
                if keyword in fn_lower:
                    return "helv"
            for keyword in self.SERIF_KEYWORDS:
                if keyword in fn_lower:
                    return "tiro"
            for keyword in self.MONO_KEYWORDS:
                if keyword in fn_lower:
                    return "cour"

            # ── Step 3: unknown font → fall back to Helvetica ─────────────
            print(
                f"  ⚠️  Font_Mapper: unrecognised font '{font_name}' "
                f"on page {page}, bbox {bbox} — falling back to 'helv'."
            )
            return "helv"

        except Exception as exc:  # noqa: BLE001
            print(
                f"  ⚠️  Font_Mapper: exception resolving font '{font_name}' "
                f"on page {page}, bbox {bbox}: {exc} — falling back to 'helv'."
            )
            return "helv"


# ── Background_Sampler ───────────────────────────────────────────────────────

class Background_Sampler:
    """
    Samples the pixel color at the four corners of a block's bounding box
    to determine the correct erase fill color for the PDF writer.

    Requirements 5.1 – 5.6:
    - Renders the page to a pixmap via ``page.get_pixmap()``.
    - Clamps corner coordinates to page bounds before sampling.
    - Returns ``(r, g, b)`` floats in ``[0, 1]`` when all four corners share
      the same RGB color (exact equality of all three channels).
    - Returns ``None`` when corners differ (non-uniform background).
    - Returns ``None`` (no exception) for zero-width or zero-height bbox.
    - Returns ``None`` and logs a warning on any exception.
    """

    def sample(
        self,
        page: "fitz.Page",
        bbox: "tuple[float, float, float, float]",
    ) -> "tuple[float, float, float] | None":
        """
        Sample the four corners of *bbox* on *page* and return a uniform
        background color, or ``None`` if the background is non-uniform.

        Parameters
        ----------
        page : fitz.Page
            The PyMuPDF page object to sample.
        bbox : tuple[float, float, float, float]
            Bounding box ``(x0, y0, x1, y1)`` in PDF user-space coordinates.

        Returns
        -------
        tuple[float, float, float] | None
            ``(r, g, b)`` floats in ``[0, 1]`` if all four corners match;
            ``None`` otherwise.
        """
        try:
            x0, y0, x1, y1 = bbox

            # Return None (no exception) for degenerate bboxes (Req 5.5).
            if x1 <= x0 or y1 <= y0:
                return None

            # Render the page to a pixmap (Req 5.1).
            pix = page.get_pixmap()
            pw = pix.width
            ph = pix.height

            # Page bounds for clamping (Req 5.1).
            page_rect = page.rect
            page_x0 = page_rect.x0
            page_y0 = page_rect.y0
            page_x1 = page_rect.x1
            page_y1 = page_rect.y1

            # The pixmap covers the page rect; we need to convert PDF
            # coordinates to pixel coordinates.
            # pixel_x = (pdf_x - page_x0) / (page_x1 - page_x0) * (pw - 1)
            page_w = page_x1 - page_x0
            page_h = page_y1 - page_y0

            def _pdf_to_pixel(px, py):
                """Convert PDF coordinates to integer pixel indices, clamped."""
                # Clamp to page bounds first (Req 5.1)
                cx = max(page_x0, min(px, page_x1))
                cy = max(page_y0, min(py, page_y1))
                # Map to pixel space
                ix = int((cx - page_x0) / page_w * (pw - 1)) if page_w > 0 else 0
                iy = int((cy - page_y0) / page_h * (ph - 1)) if page_h > 0 else 0
                # Final clamp to pixmap dimensions
                ix = max(0, min(ix, pw - 1))
                iy = max(0, min(iy, ph - 1))
                return ix, iy

            # Sample the four corners of the bbox.
            corners = [
                _pdf_to_pixel(x0, y0),  # top-left
                _pdf_to_pixel(x1, y0),  # top-right
                _pdf_to_pixel(x0, y1),  # bottom-left
                _pdf_to_pixel(x1, y1),  # bottom-right
            ]

            # Read pixel samples; pix.pixel(x, y) returns a tuple of channel
            # values (0–255 per channel for RGB/RGBA pixmaps).
            samples = [pix.pixel(cx, cy) for cx, cy in corners]

            # Normalise to [0, 1] using the first three channels (R, G, B).
            def _to_float(sample):
                return (sample[0] / 255.0, sample[1] / 255.0, sample[2] / 255.0)

            ref = _to_float(samples[0])
            for s in samples[1:]:
                if _to_float(s) != ref:
                    # Corners differ → non-uniform background (Req 5.2 / 5.3)
                    return None

            # All four corners match → return the uniform color (Req 5.2).
            return ref

        except Exception as exc:  # noqa: BLE001
            print(
                f"  ⚠️  Background_Sampler: exception sampling bbox {bbox}: "
                f"{exc} — falling back to white fill."
            )
            return None


def _split_long_text(text, max_words=80):
    """
    Break a long paragraph into sentence-boundary chunks of ≤ max_words.
    This prevents NLLB from trying to fit a 400-word paragraph into one decode.

    .. deprecated::
        Use ``Chunk_Splitter().split()`` instead.  This function is kept only
        for backwards-compatibility and is no longer called by the pipeline.
    """
    sentences = _re2.split(r'(?<=[.!?])\s+', text.strip())
    chunks, cur, cur_len = [], [], 0
    for s in sentences:
        wc = len(s.split())
        if cur_len + wc > max_words and cur:
            chunks.append(" ".join(cur))
            cur, cur_len = [], 0
        cur.append(s)
        cur_len += wc
    if cur:
        chunks.append(" ".join(cur))
    return chunks


class Chunk_Splitter:
    """
    Splits a block of text into sentence-boundary-aligned chunks.

    Rules (Requirements 1.1 – 1.6):
    - Split only at sentence-ending punctuation (. ! ?) followed by
      whitespace or end-of-string.
    - Preferred maximum chunk size is ``max_tokens`` whitespace-delimited
      tokens.
    - When no sentence boundary exists within ``max_tokens`` tokens, extend
      to the next available boundary up to ``hard_cap`` tokens.
    - When no sentence-ending punctuation exists anywhere in the text, return
      ``[text]`` (the whole block as a single chunk).
    - Enforce a minimum chunk size of ``min_tokens`` tokens by merging a
      too-small chunk forward into the next chunk.
    - The complete character-for-character content of the original block is
      preserved across all chunks (no characters dropped or duplicated).
    """

    # Matches the position immediately after . ! ? when followed by
    # whitespace or end-of-string.
    SENTENCE_END = re.compile(r'(?<=[.!?])(?=\s|$)')

    def split(self, text: str, max_tokens: int = 80, hard_cap: int = 150,
              min_tokens: int = 5) -> list:
        """
        Split *text* into chunks respecting sentence boundaries.

        Parameters
        ----------
        text : str
            The source block text to split.
        max_tokens : int
            Preferred maximum number of whitespace-delimited tokens per chunk.
        hard_cap : int
            Absolute maximum tokens per chunk when no boundary is found within
            ``max_tokens``.
        min_tokens : int
            Minimum tokens per chunk; chunks smaller than this are merged
            forward into the following chunk.

        Returns
        -------
        list[str]
            A list of chunk strings whose concatenation (joined with a single
            space after normalising whitespace) equals the original text.
        """
        # Normalise internal whitespace so token counts are consistent, but
        # preserve the original text for the no-boundary fast-path.
        words = text.split()
        total = len(words)

        # Fast-path 1: text is short enough to be a single chunk.
        if total <= max_tokens:
            return [text]

        # Fast-path 2: no sentence-ending punctuation anywhere → single chunk.
        if not self.SENTENCE_END.search(text):
            return [text]

        # ── Build candidate split points ──────────────────────────────────
        # We work on the *word* level.  First, reconstruct a normalised
        # version of the text (words joined by single spaces) so that
        # character-level regex positions map cleanly to word indices.
        normalised = " ".join(words)

        # Find all character positions in `normalised` that are valid
        # sentence-end split points.
        boundary_char_positions = [m.start() for m in self.SENTENCE_END.finditer(normalised)]

        # Convert character positions to word indices.
        # A boundary at char position p means the split happens *after* the
        # word that ends at or before p.  We find the word index by counting
        # spaces up to p.
        boundary_word_indices = []
        for pos in boundary_char_positions:
            # Count how many words are in normalised[:pos]
            word_idx = len(normalised[:pos].split())
            if word_idx > 0 and word_idx not in boundary_word_indices:
                boundary_word_indices.append(word_idx)

        if not boundary_word_indices:
            # No usable boundaries found after conversion → single chunk.
            return [text]

        # ── Greedy chunking ───────────────────────────────────────────────
        chunks = []
        start = 0  # word index of the current chunk's start

        while start < total:
            remaining = total - start

            # If what's left fits within max_tokens, take it all.
            if remaining <= max_tokens:
                chunks.append(" ".join(words[start:]))
                break

            # Look for the last boundary within [start+1 .. start+max_tokens].
            preferred_end = start + max_tokens  # exclusive upper bound (word index)
            candidate = None
            for bi in boundary_word_indices:
                if start < bi <= preferred_end:
                    candidate = bi  # keep the *last* one within the window

            if candidate is not None:
                # Found a boundary within the preferred window.
                chunks.append(" ".join(words[start:candidate]))
                start = candidate
                continue

            # No boundary within max_tokens → extend to hard_cap.
            hard_end = start + hard_cap
            for bi in boundary_word_indices:
                if preferred_end < bi <= hard_end:
                    candidate = bi
                    break  # take the *first* one beyond max_tokens

            if candidate is not None:
                chunks.append(" ".join(words[start:candidate]))
                start = candidate
                continue

            # No boundary within hard_cap either → force-split at hard_cap.
            end = min(start + hard_cap, total)
            chunks.append(" ".join(words[start:end]))
            start = end

        # ── Enforce minimum chunk size ────────────────────────────────────
        # Merge any chunk that is too small into the *next* chunk.
        merged: list = []
        for chunk in chunks:
            if merged and len(merged[-1].split()) < min_tokens:
                # Previous chunk is too small → merge current into it.
                merged[-1] = merged[-1] + " " + chunk
            else:
                merged.append(chunk)

        # Edge case: the *last* chunk may still be too small after the loop.
        # Merge it backward into the second-to-last chunk.
        if len(merged) > 1 and len(merged[-1].split()) < min_tokens:
            last = merged.pop()
            merged[-1] = merged[-1] + " " + last

        return merged


# ── Context_Buffer ────────────────────────────────────────────────────────────

class Context_Buffer:
    """
    Sliding window of the last N translated blocks used as a context hint
    for the next translation call.

    window_size: number of preceding translated blocks to retain (default 2).
    """

    def __init__(self, window_size: int = 2):
        self._buffer: deque = deque(maxlen=window_size)

    def push(self, translated_text: str) -> None:
        """Add a newly translated block to the buffer."""
        self._buffer.append(translated_text)

    def get_hint(self) -> str:
        """Return buffer contents joined by ' ||| ', or '' if empty."""
        if not self._buffer:
            return ""
        return " ||| ".join(self._buffer)

    def clear(self) -> None:
        """Reset the buffer (called at the start of each document job)."""
        self._buffer.clear()


# ── Core translation ──────────────────────────────────────────────────────────

def _translate_single(text, src_code, tgt_code, context_hint=""):
    """
    Translate a single piece of text with anti-hallucination generation params.

    Key improvements over previous version:
      - repetition_penalty=1.3  → penalises repeated n-grams during beam search
      - no_repeat_ngram_size=4  → hard-blocks any 4-gram from repeating
      - Dynamic max_new_tokens  → capped at 2× the input length, not a fixed 400
      - Splits long paragraphs before encoding so NLLB never tries to decode
        a 400-token paragraph in one shot (which is what caused the 'winds' loop)
      - context_hint: prepended to source text with ' ||| ' delimiter; truncated
        from the front when combined token count exceeds 400 (Requirement 2.2–2.3)
    """
    tokenizer.src_lang = src_code
    forced_id = tokenizer.convert_tokens_to_ids(tgt_code)

    # Split the source text into sentence-boundary chunks first (Req 1.1–1.6).
    # The context hint is applied per-chunk below so that the hint is only
    # prepended to the first chunk (the hint is about the preceding blocks,
    # not about each individual chunk of the current block).
    text_chunks = Chunk_Splitter().split(text)

    # ── Context hint: prepend to first chunk and enforce 400-token budget ─────
    # Build the first chunk's input with the context hint prepended.
    # If the combined token count exceeds 400, truncate the hint from the front
    # (oldest context first) one word at a time until it fits.
    chunks = []
    for idx, chunk in enumerate(text_chunks):
        if context_hint and idx == 0:
            combined = context_hint + " ||| " + chunk
            # Check token count; truncate hint from front if over budget
            token_ids = tokenizer(combined, return_tensors="pt",
                                  add_special_tokens=True)["input_ids"][0]
            if len(token_ids) > 400:
                hint_words = context_hint.split()
                while hint_words:
                    hint_words.pop(0)  # drop oldest word from front
                    if hint_words:
                        combined = " ".join(hint_words) + " ||| " + chunk
                    else:
                        combined = chunk
                    token_ids = tokenizer(combined, return_tensors="pt",
                                          add_special_tokens=True)["input_ids"][0]
                    if len(token_ids) <= 400:
                        break
            chunks.append(combined)
        else:
            chunks.append(chunk)

    translated_chunks = []
    for chunk in chunks:
        inputs = tokenizer(
            chunk,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=400,
        ).to(device)

        input_len = inputs["input_ids"].shape[1]
        # Cap output at 2× the source tokens — prevents runaway generation
        max_new = min(max(input_len * 2, 30), 400)

        with torch.no_grad():
            output_ids = model.generate(
                **inputs,
                forced_bos_token_id=forced_id,
                max_new_tokens=max_new,
                num_beams=4,
                early_stopping=True,
                repetition_penalty=1.3,      # ← penalises repeat phrases
                no_repeat_ngram_size=4,      # ← hard-blocks 4-gram repeats
                length_penalty=1.0,
            )

        raw = tokenizer.batch_decode(output_ids, skip_special_tokens=True)[0]
        clean = _remove_repetition_loops(raw)
        translated_chunks.append(clean)

    return " ".join(translated_chunks)


def batch_translate_blocks(blocks, source_lang, target_lang, batch_size=4,
                           context_window=1, glossary_store=None,
                           context_buffer=None):
    """
    Translate all blocks with context-aware batching.

    context_window: number of preceding blocks to show as context hint
    (currently passed as metadata; can be used for prompt-based models).
    glossary_store: optional Glossary_Store instance; when provided, apply()
    is called on each translated block text after _translate_single() returns.
    context_buffer: optional Context_Buffer instance; when provided, the hint
    from the buffer is prepended to each source block before encoding, and
    each translated block is pushed into the buffer after translation.
    """
    if not blocks:
        return []

    src_code = LANGUAGES[source_lang]
    tgt_code = LANGUAGES[target_lang]
    total = len(blocks)
    translated_blocks = []

    for i, block in enumerate(blocks):
        print(f"  Translating block {i+1}/{total}...", end="\r", flush=True)

        # Retrieve context hint from the buffer (empty string if no buffer or empty)
        hint = context_buffer.get_hint() if context_buffer is not None else ""

        translated_text = _translate_single(
            block["text"], src_code, tgt_code, context_hint=hint
        )

        # Push the translated text into the context buffer for subsequent blocks
        if context_buffer is not None:
            context_buffer.push(translated_text)

        # Apply glossary substitution after translation
        if glossary_store is not None:
            translated_text = glossary_store.apply(translated_text)

        new_block = {
            "type":  block["type"],
            "text":  translated_text,
            "style": block.get("style", {}),
        }
        if "position" in block:
            new_block["position"] = block["position"]
            new_block["page"]     = block["page"]
        translated_blocks.append(new_block)

    print(f"\n  ✓ Translation complete! ({total} blocks)")
    return translated_blocks

# Cell 8 (v2 – Textbox + Full-Block Erase): Output Writers
# ─────────────────────────────────────────────────────────────────────────────
# OUTPUT WRITERS
# ─────────────────────────────────────────────────────────────────────────────


# ── Style_Mapper ──────────────────────────────────────────────────────────────

class Style_Mapper:
    """
    Maps DOCX paragraph style names from the source document to the output
    document's available styles.

    Requirements 7.1, 7.2, 7.3:
    - Return ``style_name`` unchanged when it exists in ``available_styles``.
    - Return ``"Normal"`` when ``style_name`` is ``None``, an empty string,
      or a name that does not exist in ``available_styles``.
    """

    def resolve(self, style_name: str | None, available_styles: set) -> str:
        """
        Return the style name to apply to the output paragraph.

        Parameters
        ----------
        style_name : str | None
            The paragraph style name extracted from the source document.
        available_styles : set[str]
            The set of style names present in the output document.

        Returns
        -------
        str
            ``style_name`` if it is in ``available_styles``; ``"Normal"``
            otherwise (including when ``style_name`` is ``None`` or ``""``).
        """
        if not style_name:
            return "Normal"
        if style_name in available_styles:
            return style_name
        return "Normal"


def write_docx(blocks, output_file, original_file=None):
    """Write blocks to a DOCX file with preserved styles, formatting, and tables.

    Reconstructs:
    - Paragraphs with paragraph style (via Style_Mapper), alignment,
      space_before, space_after, and run-level font color (Requirements 7.2–7.6).
    - Tables grouped by table_index, with merged cell spans and run-level
      bold / font_size (Requirements 8.2–8.6).

    Parameters
    ----------
    blocks : list[dict]
        Translated blocks as produced by ``batch_translate_blocks()``.
        Each block has ``"type"`` of ``"paragraph"`` or ``"table_cell"``.
    output_file : str
        Path to write the output ``.docx`` file.
    original_file : str | None
        Unused; kept for API compatibility.
    """
    doc = Document()
    style_mapper = Style_Mapper()

    # Build the set of available style names in the output document once.
    available_styles: set = {s.name for s in doc.styles}

    # ── Separate paragraph blocks from table_cell blocks ─────────────────────
    paragraph_blocks = [b for b in blocks if b.get("type") == "paragraph"]
    table_blocks     = [b for b in blocks if b.get("type") == "table_cell"]

    # ── Write paragraph blocks ────────────────────────────────────────────────
    for block in paragraph_blocks:
        style_info = block.get("style") or {}

        # Resolve paragraph style (Requirements 7.2, 7.3)
        style_name = style_info.get("style_name")
        resolved_style = style_mapper.resolve(style_name, available_styles)

        # Add paragraph with the resolved style.
        para = doc.add_paragraph(block["text"], style=resolved_style)

        # Copy alignment when set (Requirement 7.4)
        alignment = style_info.get("alignment")
        if alignment is not None:
            para.alignment = alignment

        # Copy paragraph spacing when set (Requirement 7.5)
        space_before = style_info.get("space_before")
        if space_before is not None:
            para.paragraph_format.space_before = space_before

        space_after = style_info.get("space_after")
        if space_after is not None:
            para.paragraph_format.space_after = space_after

        # Apply run-level formatting (bold, font_size, font_color)
        if para.runs:
            run = para.runs[0]

            # Bold (only set when explicitly True in source)
            if style_info.get("bold"):
                run.bold = True

            # Font size (only set when explicitly provided)
            font_size = style_info.get("font_size")
            if font_size is not None:
                run.font.size = font_size

            # Font color (Requirement 7.6)
            font_color = style_info.get("font_color")
            if font_color is not None:
                run.font.color.rgb = font_color

    # ── Write table blocks (Requirements 8.2–8.6) ────────────────────────────
    if table_blocks:
        # Group cells by table_index, preserving insertion order.
        tables_dict: dict = {}
        for cell_block in table_blocks:
            tidx = cell_block["table_index"]
            if tidx not in tables_dict:
                tables_dict[tidx] = []
            tables_dict[tidx].append(cell_block)

        # Process tables in ascending table_index order (Requirement 8.6).
        for tidx in sorted(tables_dict.keys()):
            cells = tables_dict[tidx]

            # Determine table dimensions from the cell metadata.
            max_row = max(c["row"] for c in cells)
            max_col = max(c["col"] for c in cells)
            num_rows = max_row + 1
            num_cols = max_col + 1

            # Add the table to the document (appended at current body end).
            table = doc.add_table(rows=num_rows, cols=num_cols)

            # Build a lookup: (row, col) → cell_block for fast access.
            cell_map: dict = {(c["row"], c["col"]): c for c in cells}

            for row_idx in range(num_rows):
                for col_idx in range(num_cols):
                    cell_block = cell_map.get((row_idx, col_idx))
                    if cell_block is None:
                        continue

                    tbl_cell = table.cell(row_idx, col_idx)

                    # Write cell text (Requirement 8.2: empty cells stay empty)
                    cell_text = cell_block.get("text", "").strip()
                    if cell_text:
                        # Clear the default empty paragraph and set text.
                        tbl_cell.paragraphs[0].clear()
                        run = tbl_cell.paragraphs[0].add_run(cell_text)

                        # Apply run-level bold and font_size (Requirement 8.4)
                        cell_style = cell_block.get("style") or {}
                        cell_bold = cell_style.get("bold")
                        if cell_bold is not None:
                            run.bold = cell_bold

                        cell_font_size = cell_style.get("font_size")
                        if cell_font_size is not None:
                            run.font.size = cell_font_size

                    # Apply merged cell spans (Requirement 8.3)
                    col_span = cell_block.get("col_span", 1)
                    row_span = cell_block.get("row_span", 1)

                    if col_span > 1:
                        # Merge horizontally: merge this cell with the cells
                        # to its right.
                        end_col = col_idx + col_span - 1
                        if end_col < num_cols:
                            merge_target = table.cell(row_idx, end_col)
                            tbl_cell.merge(merge_target)

                    if row_span > 1:
                        # Merge vertically: merge this cell with the cells below.
                        end_row = row_idx + row_span - 1
                        if end_row < num_rows:
                            # After a horizontal merge, tbl_cell may have
                            # changed; re-fetch from the table.
                            tbl_cell_v = table.cell(row_idx, col_idx)
                            merge_target_v = table.cell(end_row, col_idx)
                            tbl_cell_v.merge(merge_target_v)

    doc.save(output_file)


def _resolve_overflow(
    page,
    block_text: str,
    x0: float, y0: float, x1: float, y1: float,
    font_size: float,
    resolved_font: str,
    other_bboxes: list,
    page_height: float,
    original_doc,
    page_num: int,
    bg_color,
    initial_remaining: float,
) -> dict:
    """
    Resolve text overflow for a single block using the containment algorithm
    (Requirements 6.1–6.6).

    This function is extracted from ``write_pdf_preserved()`` so that the
    overflow logic can be unit-tested independently of the full PDF pipeline.

    Algorithm:
      1. ``insert_textbox()`` with original rect; if ``remaining >= 0``, done.
      2. Check if expanding downward by ``abs(remaining) + font_size`` would
         bring the bottom within 2pt of any other block on the page.
      3. If no collision: expand rect and re-insert.
      4. If collision: reduce ``font_size`` by 1pt and retry from step 1;
         repeat until ``font_size == 6``.
      5. If still overflowing at 6pt: insert remaining text in a continuation
         box of the same width placed 4pt below the last block on the page.
      6. If continuation box extends beyond page bottom: clip to page boundary
         and log a warning.

    Parameters
    ----------
    page : fitz.Page
        The output page to draw on.
    block_text : str
        The translated text to insert.
    x0, y0, x1, y1 : float
        Original block bounding box coordinates.
    font_size : float
        Starting font size (points).
    resolved_font : str
        Font name to use for ``insert_textbox()``.
    other_bboxes : list[list[float]]
        Bounding boxes of all other blocks on the page (read-only).
    page_height : float
        Height of the page in points.
    original_doc : fitz.Document
        The original PDF document (used for clip-and-redraw background).
    page_num : int
        0-based page number (used for clip-and-redraw and warning messages).
    bg_color : tuple[float, float, float] | None
        Uniform background color, or ``None`` for clip-and-redraw.
    initial_remaining : float
        The ``remaining`` value returned by the initial ``insert_textbox()``
        call (must be negative to enter this function).

    Returns
    -------
    dict with keys:
        ``resolved``      : bool — True if text fits without a continuation box.
        ``final_font``    : float — The font size used for the final insertion.
        ``expanded``      : bool — True if the rect was expanded downward.
        ``continuation``  : bool — True if a continuation box was created.
        ``clipped``       : bool — True if the continuation box was clipped.
        ``cont_rect``     : fitz.Rect | None — The continuation box rect, if any.
    """
    MIN_FONT = 6.0

    def _would_collide(new_bottom: float) -> bool:
        """Return True if expanding to new_bottom would be within 2pt of any
        block below the current block (Requirement 6.2)."""
        for ob in other_bboxes:
            ob_top = ob[1]  # y0 of the other block
            if ob_top > y0:  # only blocks below current
                if ob_top - new_bottom < 2:
                    return True
        return False

    def _erase_and_redraw(rect: "fitz.Rect") -> None:
        """Erase the given rect using the background color or clip-and-redraw."""
        if bg_color is not None:
            page.draw_rect(rect, color=None, fill=bg_color)
        else:
            page.show_pdf_page(
                rect, original_doc, page_num,
                clip=rect, keep_proportion=True,
            )

    current_font = font_size
    fit_remaining = initial_remaining  # negative at entry
    resolved = False
    expanded = False
    continuation = False
    clipped = False
    cont_rect = None

    # Step 1: if initial_remaining >= 0, text already fits — nothing to do.
    if initial_remaining >= 0:
        return {
            "resolved":     True,
            "final_font":   current_font,
            "expanded":     False,
            "continuation": False,
            "clipped":      False,
            "cont_rect":    None,
        }

    while fit_remaining < 0 and not resolved:
        # Step 2: check if expanding downward would collide.
        expand_needed = abs(fit_remaining) + current_font
        candidate_bottom = y1 + expand_needed

        if not _would_collide(candidate_bottom):
            # Step 3: no collision — expand rect and re-insert.
            expanded_rect = fitz.Rect(x0, y0, x1, candidate_bottom)
            expand_erase = fitz.Rect(
                x0 - 2, y0 - 2, x1 + 2, expanded_rect.y1 + 4
            )
            _erase_and_redraw(expand_erase)
            page.insert_textbox(
                expanded_rect,
                block_text,
                fontsize=current_font,
                fontname=resolved_font,
                color=(0, 0, 0),
                align=0,
            )
            resolved = True
            expanded = True
        else:
            # Step 4: collision — reduce font size by 1pt and retry from
            # step 1 (original rect), unless already at MIN_FONT.
            if current_font <= MIN_FONT:
                # Cannot reduce further; exit loop for step 5.
                break
            current_font = max(current_font - 1.0, MIN_FONT)
            # Step 1 retry: insert with original rect at new font.
            text_rect_retry = fitz.Rect(x0, y0, x1, y1)
            fit_remaining = page.insert_textbox(
                text_rect_retry,
                block_text,
                fontsize=current_font,
                fontname=resolved_font,
                color=(0, 0, 0),
                align=0,
            )
            if fit_remaining >= 0:
                # Text fits at the reduced font size — done.
                resolved = True

    if not resolved:
        # Step 5: still overflowing at 6pt — continuation box.
        # Find the bottom of the last block on the page.
        if other_bboxes:
            last_bottom = max(ob[3] for ob in other_bboxes)
        else:
            last_bottom = y1

        cont_top    = last_bottom + 4.0
        cont_bottom = cont_top + abs(fit_remaining) + MIN_FONT
        cont_rect   = fitz.Rect(x0, cont_top, x1, cont_bottom)

        # Step 6: clip to page boundary if needed (Req 6.6).
        if cont_bottom > page_height:
            print(
                f"  ⚠️  Continuation box clipped to page boundary "
                f"(page {page_num}, bbox [{x0}, {y0}, {x1}, {y1}])"
            )
            cont_rect = fitz.Rect(x0, cont_top, x1, page_height)
            clipped = True

        # Erase the continuation area and insert remaining text.
        cont_erase = fitz.Rect(
            x0 - 2, cont_rect.y0 - 2, x1 + 2, cont_rect.y1 + 4
        )
        _erase_and_redraw(cont_erase)
        page.insert_textbox(
            cont_rect,
            block_text,
            fontsize=MIN_FONT,
            fontname=resolved_font,
            color=(0, 0, 0),
            align=0,
        )
        continuation = True

    return {
        "resolved":     resolved,
        "final_font":   current_font,
        "expanded":     expanded,
        "continuation": continuation,
        "clipped":      clipped,
        "cont_rect":    cont_rect,
    }


def write_pdf_preserved(blocks, original_pdf_path, output_file):
    """
    Overlay translated text on the original PDF, preserving layout.

    FIX vs previous version:
      - OLD: insert_text() at a single Point → no word-wrap → text overflows
             horizontally off the page for longer translations.
             White rect was sized from the tiny 50-char search bbox.
      - NEW: insert_textbox() with the FULL block bbox → automatic word-wrap
             within the original text area.  If the translated text is longer
             than the original block, the box expands downward and we also
             expand the erasing rect so no artefacts show through.

    Font matching (Requirements 4.1–4.5):
      - Font_Mapper.resolve() is called per block using the font name stored
        in block["style"]["font"] (extracted by read_pdf() from span metadata).
      - The set of embedded font names for each page is obtained via
        fitz.Document.get_page_fonts() and passed to Font_Mapper.resolve().
    """
    original_doc = fitz.open(original_pdf_path)
    output_doc   = fitz.open()

    # Instantiate Font_Mapper and Background_Sampler once; reuse across all pages and blocks.
    font_mapper = Font_Mapper()
    bg_sampler = Background_Sampler()

    for page_num in range(len(original_doc)):
        original_page = original_doc[page_num]

        # New blank page with identical dimensions
        new_page = output_doc.new_page(
            width=original_page.rect.width,
            height=original_page.rect.height
        )

        # Stamp the original page content (images, graphics, background) first
        new_page.show_pdf_page(
            new_page.rect,
            original_doc,
            page_num,
            keep_proportion=True
        )

        # Build the set of font names embedded in this page (Requirement 4.2).
        # get_page_fonts() returns a list of tuples; index 3 is the font name.
        try:
            page_font_tuples = original_doc.get_page_fonts(page_num)
            embedded_fonts: set = {
                tup[3] for tup in page_font_tuples if tup[3]
            }
        except Exception:
            embedded_fonts = set()

        page_blocks = [b for b in blocks if b.get("page") == page_num]

        for block in page_blocks:
            try:
                bbox = block.get("position", [50, 50, 500, 100])
                x0, y0, x1, y1 = bbox

                style     = block.get("style", {})
                font_size = float(style.get("font_size", 11) or 11)
                font_size = max(6.0, min(font_size, 72.0))  # safety clamp

                # ── Resolve font name via Font_Mapper (Requirements 4.1–4.5) ─
                raw_font_name = style.get("font", "helv") or "helv"
                resolved_font = font_mapper.resolve(
                    raw_font_name, embedded_fonts,
                    page=page_num, bbox=bbox
                )

                # ── Step 1: erase original text using background color ──────
                # Sample the background color at the four corners of the block.
                # If all corners share the same color, use it as the fill.
                # Otherwise, use the clip-and-redraw strategy (Req 5.2–5.4).
                # For zero-width/height bboxes, skip erasure (Req 5.5).
                erase_rect = fitz.Rect(x0 - 2, y0 - 2, x1 + 2, y1 + 4)

                if x1 > x0 and y1 > y0:
                    bg_color = bg_sampler.sample(original_page, (x0, y0, x1, y1))
                else:
                    bg_color = None  # zero-width or zero-height — skip erasure (Req 5.5)

                if bg_color is not None:
                    # Uniform background — use sampled color as fill (Req 5.2)
                    new_page.draw_rect(erase_rect, color=None, fill=bg_color)
                elif x1 > x0 and y1 > y0:
                    # Non-uniform background — clip-and-redraw strategy (Req 5.3–5.4)
                    # Re-stamp the original page content clipped to the block region,
                    # then the translated text will be drawn on top.
                    clip_rect = fitz.Rect(x0 - 2, y0 - 2, x1 + 2, y1 + 4)
                    new_page.show_pdf_page(
                        clip_rect,
                        original_doc,
                        page_num,
                        clip=clip_rect,
                        keep_proportion=True,
                    )
                # If zero-width/height, skip erasure entirely (Req 5.5)

                # ── Step 2: insert translated text with word-wrap ───────────
                # insert_textbox() wraps text inside the rect automatically.
                # It returns the amount of space remaining (negative = overflow).
                text_rect = fitz.Rect(x0, y0, x1, y1)

                remaining = new_page.insert_textbox(
                    text_rect,
                    block["text"],
                    fontsize=font_size,
                    fontname=resolved_font,
                    color=(0, 0, 0),
                    align=0,        # 0=left, 1=centre, 2=right
                )

                # ── Steps 1–6: overflow containment (Requirements 6.1–6.6) ──
                # Delegate to _resolve_overflow() which implements the full
                # algorithm and is independently unit-testable.
                if remaining < 0:
                    # Collect bounding boxes of all OTHER blocks on this page
                    # (read-only — we never modify them, Requirement 6.5).
                    other_bboxes = [
                        b.get("position", [])
                        for b in page_blocks
                        if b is not block and b.get("position")
                    ]

                    _resolve_overflow(
                        page=new_page,
                        block_text=block["text"],
                        x0=x0, y0=y0, x1=x1, y1=y1,
                        font_size=font_size,
                        resolved_font=resolved_font,
                        other_bboxes=other_bboxes,
                        page_height=new_page.rect.height,
                        original_doc=original_doc,
                        page_num=page_num,
                        bg_color=bg_color,
                        initial_remaining=remaining,
                    )

            except Exception as e:
                print(f"  ⚠️  Layout error for block: {str(e)[:100]}")
                try:
                    # Best-effort fallback: left margin, approximate y
                    fallback_rect = fitz.Rect(50, y0, x1, y1 + 60)
                    new_page.insert_textbox(
                        fallback_rect,
                        block["text"],
                        fontsize=11,
                        fontname="helv",
                        color=(0, 0, 0),
                    )
                except Exception:
                    pass

    output_doc.save(output_file)
    output_doc.close()
    original_doc.close()
    print("  ✓ PDF saved with layout preservation")


def write_txt(blocks, output_file):
    """Write blocks to plain text."""
    with open(output_file, "w", encoding="utf-8") as f:
        for block in blocks:
            if isinstance(block, dict):
                f.write(block.get("text", "") + "\n\n")


def write_csv(blocks_data, output_file):
    """Write translated CSV data preserving row/column structure."""
    with open(output_file, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(blocks_data)


def choose_output_path(input_file, output_dir=""):
    """Decide output filename based on input format capabilities."""
    base = os.path.splitext(os.path.basename(input_file))[0]
    ext  = os.path.splitext(input_file)[1].lower()
    WRITABLE_FORMATS = {
        ".docx": ".docx",
        ".txt":  ".txt",
        ".md":   ".md",
        ".pdf":  ".pdf",
        ".csv":  ".csv",
        ".rtf":  ".docx",
        ".odt":  ".docx",
    }
    out_ext  = WRITABLE_FORMATS.get(ext, ".docx")
    out_name = f"translated_{base}{out_ext}"
    return os.path.join(output_dir, out_name) if output_dir else out_name


def reconstruct_document(blocks, output_file, original_file=None, original_ext=None):
    """Write translated blocks to the appropriate output format."""
    ext = os.path.splitext(output_file)[1].lower()
    if ext == ".docx":
        write_docx(blocks, output_file, original_file)
    elif ext == ".pdf" and original_file:
        write_pdf_preserved(blocks, original_file, output_file)
    elif ext in {".txt", ".md"}:
        write_txt(blocks, output_file)
    elif ext == ".csv":
        if isinstance(blocks, list) and blocks and "data" in blocks[0]:
            write_csv(blocks[0]["data"], output_file)
        else:
            write_csv(blocks, output_file)
    else:
        write_txt(blocks, output_file)

# Cell 9 (v2): Pipeline
# ─────────────────────────────────────────────────────────────────────────────

# ── BLEU_Reporter ─────────────────────────────────────────────────────────────

class BLEU_Reporter:
    """
    Computes a corpus-level BLEU score for a completed translation job.

    Requirements 9.1 – 9.6:
    - Reads a plain-text reference file (one block per non-empty line).
    - Aligns translated blocks and reference lines by index up to
      ``min(len(translated_blocks), len(ref_lines))``.
    - Logs a warning when the counts differ.
    - Returns a ``sacrebleu`` corpus BLEU score in the range 0.0–100.0.
    - Returns ``None`` (and logs a warning) on any read/parse error.
    """

    def compute(
        self,
        translated_blocks: list,
        reference_file: str,
    ) -> "float | None":
        """
        Compute corpus BLEU between *translated_blocks* and *reference_file*.

        Parameters
        ----------
        translated_blocks : list[dict]
            The translated block objects produced by ``batch_translate_blocks()``.
            Each block must have a ``"text"`` key.
        reference_file : str
            Path to a plain-text file with one reference block per non-empty line.

        Returns
        -------
        float | None
            Corpus BLEU score in ``[0.0, 100.0]``, or ``None`` on error.
        """
        try:
            import sacrebleu  # noqa: PLC0415 — imported here to keep top-level optional

            # ── Read reference file ───────────────────────────────────────────
            with open(reference_file, "r", encoding="utf-8", errors="replace") as fh:
                ref_lines = [line.rstrip("\n") for line in fh if line.strip()]

        except Exception as exc:  # noqa: BLE001
            print(
                f"  ⚠️  BLEU_Reporter: cannot read reference file '{reference_file}': "
                f"{exc} — skipping BLEU computation."
            )
            return None

        try:
            # ── Align by index ────────────────────────────────────────────────
            n_hyp = len(translated_blocks)
            n_ref = len(ref_lines)
            n_aligned = min(n_hyp, n_ref)

            if n_hyp != n_ref:
                print(
                    f"  ⚠️  BLEU_Reporter: translated block count ({n_hyp}) differs from "
                    f"reference line count ({n_ref}); computing BLEU over {n_aligned} aligned pairs."
                )

            hypotheses = [translated_blocks[i]["text"] for i in range(n_aligned)]
            references = [ref_lines[i] for i in range(n_aligned)]

            if not hypotheses:
                print(
                    "  ⚠️  BLEU_Reporter: no aligned pairs to score — returning None."
                )
                return None

            # sacrebleu expects references as a list of lists (one list per
            # reference translation; here we have a single reference set).
            result = sacrebleu.corpus_bleu(hypotheses, [references])
            return result.score  # float in [0.0, 100.0]

        except Exception as exc:  # noqa: BLE001
            print(
                f"  ⚠️  BLEU_Reporter: error computing BLEU score: {exc} — returning None."
            )
            return None


def run_pipeline(input_file, source_lang, target_lang,
                 output_file=None, pdf_column_mode="auto", glossary=None,
                 reference_file=None):
    """
    Run the complete translation pipeline.

    pdf_column_mode:
      'auto'   – translate all text found (default)
      'left'   – only translate left-column text  (bilingual source PDFs)
      'right'  – only translate right-column text
      'single' – treat page as one column, no filtering

    glossary: optional list of (source_term, target_term) pairs for
      Glossary_Store. When provided, whole-word substitution is applied
      to each translated block after translation. Raises ValueError if
      the glossary contains duplicate source terms or more than 1000 pairs.

    reference_file: optional path to a plain-text reference translation file
      (one block per non-empty line). When provided, a corpus BLEU score is
      computed at the end of the pipeline and included in the result dict.

    Returns
    -------
    dict
        ``{"output_file": str, "translated_blocks": list, "bleu_score": float | None}``
    """
    if output_file is None:
        output_file = choose_output_path(input_file)

    # Build glossary store (raises ValueError early if glossary is invalid)
    if glossary is not None:
        glossary_store = Glossary_Store(glossary)
    else:
        glossary_store = None

    print("📥 Reading document…")
    data, ext = analyze_document(input_file, pdf_column_mode=pdf_column_mode)

    if ext == ".csv":
        csv_data = data
        print(f"  Found {len(csv_data.get('data', []))} rows in CSV.")
        print("🌍 Translating…")
        translated_rows = []
        for row_idx, row in enumerate(csv_data["data"]):
            translated_row = []
            for col_idx, cell in enumerate(row):
                if cell.strip() and len(cell.split()) >= 2:
                    print(f"  Translating cell [{row_idx+1},{col_idx+1}]...", end="\r")
                    translated_row.append(
                        _translate_single(cell, LANGUAGES[source_lang], LANGUAGES[target_lang])
                    )
                else:
                    translated_row.append(cell)
            translated_rows.append(translated_row)
        print("\n📄 Rebuilding CSV →", output_file)
        write_csv(translated_rows, output_file)
        print("✅ Done!")
        return {
            "output_file": output_file,
            "translated_blocks": [{"data": translated_rows}],
            "bleu_score": None,
        }

    blocks = data
    print(f"  Found {len(blocks)} text block(s) after filtering.")

    if not blocks:
        raise ValueError(
            "No translatable text extracted. "
            "If this is a scanned PDF, OCR is required. "
            "For bilingual PDFs, try pdf_column_mode='left' or 'right'."
        )

    print("🌍 Translating…")
    # Instantiate a Context_Buffer scoped to this document job (Requirement 2.1)
    ctx_buffer = Context_Buffer()
    ctx_buffer.clear()  # ensure clean state at the start of each job

    translated_blocks = batch_translate_blocks(
        blocks, source_lang, target_lang,
        glossary_store=glossary_store,
        context_buffer=ctx_buffer,
    )

    print(f"📄 Rebuilding document → {output_file}")
    reconstruct_document(translated_blocks, output_file, input_file, ext)

    # ── BLEU scoring (Requirement 9.1 – 9.6) ─────────────────────────────────
    bleu_score: "float | None" = None
    if reference_file is not None:
        bleu_reporter = BLEU_Reporter()
        bleu_score = bleu_reporter.compute(translated_blocks, reference_file)
        if bleu_score is not None:
            print(f"  📊 BLEU score: {bleu_score:.2f}")

    print("✅ Done!")
    return {
        "output_file": output_file,
        "translated_blocks": translated_blocks,
        "bleu_score": bleu_score,
    }

# Cell 10: Colab UI (v3 – with PDF Column Mode selector)
# ─────────────────────────────────────────────────────────────────────────────
if 'google.colab' in __import__('sys').modules:
    import ipywidgets as widgets
    from IPython.display import display, HTML
    from google.colab import files
    import time

    source_dropdown = widgets.Dropdown(
        options=list(LANGUAGES.keys()), description="Source:",
        style={'description_width': 'initial'}
    )
    target_dropdown = widgets.Dropdown(
        options=list(LANGUAGES.keys()), description="Target:",
        style={'description_width': 'initial'}
    )
    column_mode_dropdown = widgets.Dropdown(
        options=[
            ("Auto (translate all text found)",           "auto"),
            ("Left column only  (bilingual PDF – source side)", "left"),
            ("Right column only (bilingual PDF – target side)", "right"),
            ("Single column (no column detection)",        "single"),
        ],
        description="PDF mode:",
        style={'description_width': 'initial'},
        layout=widgets.Layout(width='500px')
    )
    supported_label = widgets.HTML(
        value="<i>Supported: .docx .pdf .txt .md .rtf .odt .csv</i>"
    )
    info_label = widgets.HTML(
        value="<b>PDF Column Mode:</b> For bilingual PDFs (e.g. original + partial translation), "
              "choose 'Left column only' to extract only the source-language side."
    )
    run_button = widgets.Button(
        description="Upload & Translate", button_style="primary",
        layout=widgets.Layout(width='200px')
    )
    output_widget = widgets.Output()

    def on_button_click(b):
        with output_widget:
            output_widget.clear_output()
            if source_dropdown.value == target_dropdown.value:
                print("⚠️  Source and target language must be different.")
                return
            print("📊 Using: NLLB-200-Distilled-600M + anti-hallucination params")
            print("─" * 60)
            print("📤 Upload your file:")
            uploaded = files.upload()
            if not uploaded:
                print("⚠️  No file uploaded.")
                return
            input_file = list(uploaded.keys())[0]
            ext = os.path.splitext(input_file)[1].lower()
            if ext not in READERS:
                print(f"❌ Unsupported format '{ext}'. Supported: {', '.join(READERS.keys())}")
                return
            output_path = choose_output_path(input_file)
            print(f"📋 Output: {os.path.basename(output_path)}")
            print(f"📐 PDF column mode: {column_mode_dropdown.value}")
            print("─" * 60)
            start = time.time()
            try:
                result = run_pipeline(
                    input_file,
                    source_dropdown.value,
                    target_dropdown.value,
                    output_path,
                    pdf_column_mode=column_mode_dropdown.value
                )
                output_file = result["output_file"]
                print(f"⏱️  {time.time()-start:.1f}s")
                print(f"✅ Done! Downloading '{os.path.basename(output_file)}'…")
                files.download(output_file)
            except Exception as e:
                import traceback
                print(f"❌ Error: {e}")
                traceback.print_exc()

    run_button.on_click(on_button_click)
    display(
        HTML("<h2>🌍 Document Translator v3</h2>"),
        supported_label, info_label,
        widgets.HBox([source_dropdown, target_dropdown]),
        column_mode_dropdown,
        run_button, output_widget
    )

    # Cell 11 (OPTIONAL UPGRADE): Claude API Translation
    # ─────────────────────────────────────────────────────────────────────────────
    try:
        from google.colab import userdata
        ANTHROPIC_API_KEY = userdata.get('ANTHROPIC_API_KEY')
    except Exception:
        ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')

    if not ANTHROPIC_API_KEY:
        print("⚠️  No ANTHROPIC_API_KEY found. Add it to Colab secrets to enable Claude translation.")
        print("   The NLLB model from Cell 3 will continue to be used.")
    else:
        import requests
        import json as _json

        def _translate_single(text, src_code, tgt_code, context_hint=""):
            """
            Claude-powered translation — overrides the NLLB version.
            Uses claude-sonnet-4-20250514 for high quality output.
            """
            CODE_TO_LANG = {v: k for k, v in LANGUAGES.items()}
            src_name = CODE_TO_LANG.get(src_code, src_code)
            tgt_name = CODE_TO_LANG.get(tgt_code, tgt_code)

            system_prompt = (
                f"You are a professional translator. Translate the following {src_name} text "
                f"into {tgt_name}. "
                "Rules:\n"
                "- Output ONLY the translated text, nothing else\n"
                "- Preserve the original formatting: dashes, ellipsis, line breaks, CAPS\n"
                "- Keep proper names (Trinka, Sam, SAMHSA, etc.) unchanged\n"
                "- Preserve the tone: children's book text should stay simple and warm\n"
                "- Do NOT add explanations, notes, or quotation marks around the output"
            )

            payload = {
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 1024,
                "system": system_prompt,
                "messages": [{"role": "user", "content": text}],
            }
            headers = {
                "x-api-key": ANTHROPIC_API_KEY,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            }
            resp = requests.post(
                "https://api.anthropic.com/v1/messages",
                headers=headers,
                json=payload,
                timeout=60,
            )
            resp.raise_for_status()
            data = resp.json()
            return data["content"][0]["text"].strip()

        print("✅ Claude API translation enabled! (claude-sonnet-4-20250514)")
        print("   All translations will now use Claude instead of NLLB.")

# Cell 12: Quick Test
# Uncomment to test:
# test_pipeline('your_file.pdf', 'Cebuano', 'English')