# -*- coding: utf-8 -*-
"""nllb-200-distilled-600M_with_blue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPwubUZua_1W-zj80Ya30d603wDoDHSZ
"""

!pip install -U transformers
!pip install sacrebleu

"""## Local Inference on GPU
Model page: https://huggingface.co/facebook/nllb-200-distilled-600M

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/facebook/nllb-200-distilled-600M)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import sacrebleu

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("facebook/nllb-200-distilled-600M")
model = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-600M")

def translate_to_cebuano(text: str) -> str:
    tokenizer.src_lang = "eng_Latn"
    inputs = tokenizer(
        text,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=400,         # input token cap — keeps encoder within NLLB's sweet spot
    )

    target_lang_id = tokenizer.convert_tokens_to_ids("ceb_Latn")

    # Dynamically size the output budget: 2× the input length, min 30, max 400
    input_len = inputs["input_ids"].shape[1]
    max_new = min(max(input_len * 2, 30), 400)

    translated_tokens = model.generate(
        **inputs,
        forced_bos_token_id=target_lang_id,
        max_new_tokens=max_new,         # only max_new_tokens — avoids the conflict warning
        num_beams=4,                    # beam search for better quality
        early_stopping=True,
        repetition_penalty=1.3,         # penalises repeated phrases
        no_repeat_ngram_size=4,         # hard-blocks 4-gram repeats
        length_penalty=1.0,
    )

    translation = tokenizer.batch_decode(translated_tokens, skip_special_tokens=True)[0]
    return translation


# === INPUT (Product Output Style) ===
english_text = """The old bookstore only opened when it rained, as if the weather itself was a secret key. Inside, dust floated like slow-moving stars between the shelves. A cat slept on top of a stack of unread letters, guarding them as if they contained forgotten stories. Every time someone entered, the clock on the wall would tick a little louder, as though noticing their presence. No one ever left the shop the same way they entered."""

# Your reference (ground truth)
cebuano_reference = """Ang karaang tindahan og libro abli ra kung mag-ulan, murag ang panahon mismo mao’y sekreto nga yawi. Sa sulod, ang abog naglutaw sama sa hinay nga mga bituon taliwala sa mga estante. Usa ka iring ang natulog ibabaw sa hugpong sa mga wala pa mabasang sulat, murag nagbantay nga naa didto ang mga nalimtan nga istorya. Matag higayon nga naay mosulod, ang orasan sa dingding murag mas kusog og tik-tak, daw nakabantay sa ilang presensya. Wala gyuy ni-agi sa tindahan nga pareho pa sa ilang pag-gawas sa una."""

# === TRANSLATION ===
cebuano_translation = translate_to_cebuano(english_text)

print("English:\n", english_text)
print("\nGenerated Cebuano:\n", cebuano_translation)
print("\nReference Cebuano:\n", cebuano_reference)


# === BLEU COMPUTATION (PARAGRAPH LEVEL) ===
bleu = sacrebleu.corpus_bleu(
    [cebuano_translation],     # prediction must be list
    [[cebuano_reference]]     # reference must be list of lists
)

print("\n=== BLEU EVALUATION ===")
print("BLEU score:", bleu.score)
print(bleu)

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import sacrebleu

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("facebook/nllb-200-distilled-600M")
model = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-600M")

# NOTE: translate_to_cebuano is already defined above with the correct params.
# This second test block reuses the same function — no redefinition needed.

# === INPUT (Second Test: Maria/Jose) ===
english_text = """Maria brought bananas to her cousin Jose. Jose lived in a farm and tended to the plants. Maria was afraid of running out of bananas, but Jose prayed and asked the plants to bear more fruits."""

# Your reference (ground truth)
cebuano_reference = """Si Maria nagdala og saging sa iyang ig-agaw nga si Jose. Si Jose nahamutang sa bukid ug magtan-aw sa mga tanom. Si Maria nahadlok nga mawad-an siya og saging, apan si Jose nang-ampo ug nangayo og pahimangno sa mga tanom nga nagdala og daghan nga saging."""

# === TRANSLATION ===
cebuano_translation = translate_to_cebuano(english_text)

print("English:\n", english_text)
print("\nGenerated Cebuano:\n", cebuano_translation)
print("\nReference Cebuano:\n", cebuano_reference)


# === BLEU COMPUTATION (PARAGRAPH LEVEL) ===
bleu = sacrebleu.corpus_bleu(
    [cebuano_translation],     # prediction must be list
    [[cebuano_reference]]     # reference must be list of lists
)

print("\n=== BLEU EVALUATION ===")
print("BLEU score:", bleu.score)
print(bleu)